### ISSUE TITLE
colors in the lib

### ISSUE THREAD

**Issue by AKBIROCK3** [Arantik/Notifier#1]
hi please could you add support for another colors type ?
since im  creating an extension for app inventor i found a problem with the colors i can't use it 
i used android.graphics.Color to use colrs like Color.BLACK But it didn't work and give an error

**Comment by Arantik** [comment]
Hello **AKBIROCK3**, Thank you for your comment, I fixed this problem and published new release: **1.0.2**
Please let me know if there was another problem.

**Comment by AKBIROCK3** [comment]
> Hello **AKBIROCK3**, Thank you for your comment, I fixed this problem and published new release: **1.0.2**
> Please let me know if there was another problem.
@Arantik  THANK YOU actually there's other problems but it related just to app inventor u should consider it if you want to support app inventor too one of thses problems is that in app inventor we can't use int for  .setImage(R.drawable.ic_bell) or             .setCustomLayout(R.layout.notifier_custom_layout)
 it can be used as String but not as an int since images and all other things doesn't have ID not like in android studio
and Hope you can make more general and not just for android studio

**Comment by Arantik** [comment]
Actually I had no plan to support app inventor. Notifier is just supported in Android Studio. But I will improve it as soon as possible. I've never used app inventor and this may take much time. Anyway, thank you for your comments.  :-)

**Comment by AKBIROCK3** [comment]
> Actually I had no plan to support app inventor. Notifier is just supported in Android Studio. But I will improve it as soon as possible. I've never used app inventor and this may take much time. Anyway, thank you for your comments. :-)

one last thing what if i want to use android drawables ? like android.R.drawable.ic_launcher
s it possible ?
cuz i tried it but it didn't work ?

**Comment by Arantik** [comment]
Yes AKBIROCK3 it is possible to set android.R.drawable.anything for notifier icon. For example, you can use:

```
new Notifier.Build(MainActivity.this)
                .setImage(android.R.drawable.ic_menu_report_image)
                .setTitle("This is title!")
                .setDescription("This is description!")
                .setEnableDimBackground(false)
                .show();
```
and the output will be:

![Screenshot_20200719_010640](https://user-images.githubusercontent.com/31391744/87861599-1504d080-c95d-11ea-9431-3deb2a180dcd.png)

I tested it in Android Studio. Maybe your problem is because you are using app inventor.

**Comment by AKBIROCK3** [comment]
i 

> Yes AKBIROCK3 it is possible to set android.R.drawable.anything for notifier icon. For example, you can use:
> 
> ```
> new Notifier.Build(MainActivity.this)
>                 .setImage(android.R.drawable.ic_menu_report_image)
>                 .setTitle("This is title!")
>                 .setDescription("This is description!")
>                 .setEnableDimBackground(false)
>                 .show();
> ```
> 
> and the output will be:
> 
> ![Screenshot_20200719_010640](https://user-images.githubusercontent.com/31391744/87861599-1504d080-c95d-11ea-9431-3deb2a180dcd.png)
> 
> I tested it in Android Studio. Maybe your problem is because you are using app inventor.

i tested it with other icons and it worked the probelm is with android.R.drawable.ic_launcher since i wanted to use my app's icon 
apparently there's no way to do it

**Comment by Arantik** [comment]
Is it possible for you to copy your app icon into the 'drawable' folder and then use it? I think your problem will be solved this way.
